### ISSUE TITLE
Unable to load library 'discord-rpc'

### ISSUE THREAD

**Issue by g33kidd** [TsundereBug/discord-intellij#18]
Here's what it gives me when I tried to enable the plugin.

IntelliJ version info:

```
IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
```

```
Plugin 'com.tsunderebug.discordintellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path (/Applications/IntelliJ IDEA CE.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna.jar:/Applications/IntelliJ IDEA CE.app/Contents/jdk/Contents/Home/lib/tools.jar)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
    at com.sun.jna.Library$Handler.<init>(Library.java:179)
    at com.sun.jna.Native.loadLibrary(Native.java:569)
    at com.sun.jna.Native.loadLibrary(Native.java:544)
    at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:144)
    at net.arikia.dev.drpc.DiscordRPC.discordInitialize(DiscordRPC.java:33)
    at com.tsunderebug.discordintellij.DiscordIntelliJ.enableRPC(DiscordIntelliJ.java:17)
    at com.tsunderebug.discordintellij.StartupShutdown.initComponent(StartupShutdown.java:9)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:497)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:454)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:406)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by s5bug** [comment]
@Vatuu any idea what's going on? Recently switched to using your RPC lib. Works on Windows and Lin.

**Comment by Vatuu** [comment]
@TsundereBug What version are you using? The path it's trying to load has never been used by me in the library.

**Comment by s5bug** [comment]
@Vatuu Latest GH release

**Comment by s5bug** [comment]
@Vatuu so afaik you named the mac lib incorrectly.

`java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path`

**Comment by OzairP** [comment]
Any status on this being fixed in the plugin itself?

**Comment by s5bug** [comment]
The update is waiting approval

**Comment by Vatuu** [comment]
@TsundereBug I've tried a few things around, and I have come to 2 possible causes of the issue.
For not, I've updated the RPC to Version 1.4.3. Let me know if it's still broken, in which case I will attempt the second approach.

Sorry for the latest issues, I don't know why everything started breaking.

**Comment by OzairP** [comment]
Updated to version 2.2 (I think this was supposed to be the fixed version?), still experiencing the same error.

**Comment by s5bug** [comment]
Yes, I need to fix with another update to the rpc lib

**Comment by s5bug** [comment]
@OzairP @g33kidd This _should_ be fixed with update 2.2.1. If you know how, you can install the update manually from this zipfile: 
[discord-intellij.zip](https://github.com/TsundereBug/discord-intellij/files/1926111/discord-intellij.zip)

**Comment by OzairP** [comment]
Updated plugin to 2.3 now but crash still persists 😕

![screenshot](https://static.ozairpatel.com/lcvlz.png)

**Comment by s5bug** [comment]
@Vatuu 2.3 is on the latest version. Any other steps that should be taken?

**Comment by g33kidd** [comment]
Can confirm as well, still getting an error, here's some more info if needed:

```
IntelliJ IDEA 2018.1.2 (Community Edition)
Build #IC-181.4668.68, built on April 24, 2018
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```
```
Plugin 'com.tsunderebug.discordintellij' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path (/Applications/IntelliJ IDEA CE.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/jna.jar:/Applications/IntelliJ IDEA CE.app/Contents/jdk/Contents/Home/lib/tools.jar)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
    at com.sun.jna.Library$Handler.<init>(Library.java:179)
    at com.sun.jna.Native.loadLibrary(Native.java:569)
    at com.sun.jna.Native.loadLibrary(Native.java:544)
    at net.arikia.dev.drpc.DiscordRPC$DLL.<clinit>(DiscordRPC.java:153)
    at net.arikia.dev.drpc.DiscordRPC.discordInitialize(DiscordRPC.java:33)
    at com.tsunderebug.discordintellij.DiscordIntelliJ.enableRPC(DiscordIntelliJ.java:17)
    at com.tsunderebug.discordintellij.StartupShutdown.initComponent(StartupShutdown.java:9)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:374)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by s5bug** [comment]
See Vatuu/discord-rpc's #12 for more info

**Comment by ren-** [comment]
Proper full URL for anyone wondering: https://github.com/Vatuu/discord-rpc/issues/12
